name: "Deploy"
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [master]
jobs:
  deploy:
    steps:
      uses: jbrooksuk/laravel-forge-action@v1.0.2
      with:
        trigger_url: ${{ secrets.FORGE_DEPLOY_WEBHOOK_URL }}