name: PHP Stan
on:
  push:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: "Run PHP Stan"
        run: |
          ./vendor/bin/phpstan analyze app tests